### ISSUE TITLE
Feature request - aim distance and shell travel time

### ISSUE THREAD

**Issue by Willster419** [chirimenmonster/wotmods-dispersionindicator#2]
Hi,
I just found this mod and started using it. Being an engineer, I love displaying all the statistics. I got a feature request for this mod. If possible, could aim distance and shell travel time be added? For example:
![image](https://user-images.githubusercontent.com/2482828/71432639-f9786680-26a8-11ea-9b57-11d3bad86881.png)

I've uploaded a py script of an xvm "plugin" for aim info that shows how they do it. I'm not a python expert, but if the imports they use are direct from the WG python environment, it may be possible to incorporate it?

Thank you!
[sight.py.txt](https://github.com/chirimenmonster/wotmods-dispersionindicator/files/3999633/sight.py.txt)

**Comment by chirimenmonster** [comment]
test "distance" is https://github.com/chirimenmonster/wotmods-dispersionindicator/releases/tag/v0.4.2-dev
others are not yet

**Comment by Willster419** [comment]
Hi,
I saw you have posted another release: https://github.com/chirimenmonster/wotmods-dispersionindicator/releases/tag/v0.4.2-dev2

I will test it later today.
Thank you!!

**Comment by chirimenmonster** [comment]
update, https://github.com/chirimenmonster/wotmods-dispersionindicator/releases/tag/v0.4.2-dev3
this version is release candidate for 0.4.2
