### ISSUE TITLE
mistaken log entry?

### ISSUE THREAD

**Issue by Willster419** [chirimenmonster/wotmods-dispersionindicator#5]
I found that my `python.log` file is being spammed with an `updateVehicleDirection` informational message:
`2020-11-14 17:05:43.140: INFO: [DispersionIndicator] updateVehicleDirection`
`2020-11-14 17:05:43.140: INFO: [DispersionIndicator] updateVehicleDirection: vehicleRYaw=0.0692802667618`

I think it comes from this line of code:
https://github.com/chirimenmonster/wotmods-dispersionindicator/blob/97635d4779bf8f9a84898ecdad979056a8ed4bf2/python/dispersionindicator/statscollector.py#L383

Was this kept by mistake? Can it be removed?

**Comment by chirimenmonster** [comment]
thanks, Willster419

**Comment by Willster419** [comment]
you're welcome!
