### ISSUE TITLE
Update for 1.13?

### ISSUE THREAD

**Issue by Willster419** [chirimenmonster/wotmods-dispersionindicator#6]
Hi,
Will there be an update for 1.13?

**Comment by chirimenmonster** [comment]
I just confirmed. It seems to work without any problems.

**Comment by Willster419** [comment]
got it, thank you!

and thank you for updating the post on your wgmods page!

![image](https://user-images.githubusercontent.com/2482828/123905600-826c0000-d927-11eb-8260-1e238e2a7d2c.png)
